apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-frontend
spec:
  replicas: 1
  selector:
    matchLabels: { app: task-manager-frontend }
  template:
    metadata:
      labels: { app: task-manager-frontend }
    spec:
      containers:
        - name: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports: [{ containerPort: 80 }]
          resources:
            requests: { cpu: "50m", memory: "32Mi" }
            limits: { cpu: "150m", memory: "64Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: task-manager-frontend
spec:
  selector: { app: task-manager-frontend }
  ports: [{ port: 80, targetPort: 80 }]
